# .github/workflows/deploy.yml
name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Adjust this if your HTML is in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
